### ISSUE TITLE
[Task] FE - OAuth Client SHA1 Keys

### ISSUE THREAD

**Issue by FarihaIS** [FarihaIS/VanRoomies#28]
Add SHA1 keys of all team members for Google Sign-In OAuth Client IDs

**Comment by dlalaj** [comment]
@MphiGithub @FarihaIS Can we get a brief idea of what is needed to be done for this step from myself and @maxcao13

**Comment by dlalaj** [comment]
Closed! Each invidual signs with their own SHA-1

**Comment by dlalaj** [comment]
653de706572d411099073e0d
